export const USER_LOGOUT = "USER_LOGOUT";

export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";

export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL";

export const PRODUCT_LIST_MENU_SUCCESS = "PRODUCT_LIST_MENU_SUCCESS";
export const PRODUCT_LIST_MENU_SHOW = "PRODUCT_LIST_MENU_SHOW";
export const PRODUCT_LIST_MENU_HIDE = "PRODUCT_LIST_MENU_HIDE";

export const RECIPES_LIST_MENU_SUCCESS = "RECIPES_LIST_MENU_SUCCESS";
export const RECIPES_LIST_MENU_SHOW = "RECIPES_LIST_MENU_SHOW";
export const RECIPES_LIST_MENU_HIDE = "RECIPES_LIST_MENU_HIDE";

export const RECIPES_ID_MENU_SUCCESS = "RECIPES_ID_MENU_SUCCESS";
export const RECIPES_ID_MENU_SHOW = "RECIPES_ID_MENU_SHOW";
export const RECIPES_ID_MENU_HIDE = "RECIPES_ID_MENU_HIDE";

export const PRODUCT_LIST_SUCCESS = "PRODUCT_LIST_SUCCESS";
export const PRODUCT_LIST_SHOW = "PRODUCT_LIST_SHOW";
export const PRODUCT_LIST_HIDE = "PRODUCT_LIST_HIDE";

export const PRODUCTS_ID_SUCCESS = "PRODUCTS_ID_SUCCESS";
export const PRODUCTS_ID_SHOW = "PRODUCTS_ID_SHOW";
export const PRODUCTS_ID_HIDE = "PRODUCTS_ID_HIDE";

export const GET_MENU_ID_SUCCESS = "GET_MENU_ID_SUCCESS";
export const GET_MENU_ID_SHOW = "GET_MENU_ID_SHOW";
export const GET_MENU_ID_HIDE = "GET_MENU_ID_HIDE";
